In [1]:
import pandas as pd
import calendar

cycle_start_day = 'Monday'
cycle_period = 7

In [2]:
def find_first_monday(year, month):
    # Get the calendar for the given month and year
    cal = calendar.monthcalendar(year, month)

    # Find the first week that has a Monday
    for week in cal:
        if week[calendar.MONDAY] != 0:
            # Return the date of the first Monday
            return week[calendar.MONDAY]

In [3]:
def get_data():
    df = pd.read_excel('/Users/jigme/Desktop/data/sales.xlsx',dtype={'Scan Code':str})
    df['Date'] = pd.to_datetime(df['Date'])
    df['Year'] = df['Date'].dt.year
    df['Month'] = df['Date'].dt.month
    df['Day'] = df['Date'].dt.day
    df['WeekDay'] = df['Date'].dt.day_of_week
    print('Year(s) : ',df['Year'].unique())
    print('Months(s) : ',df['Month'].unique())
    print('start date: ',df['Date'][0])
    print('end date: ',df['Date'][len(df)-1])
    return df

In [13]:
def calculate_cycle_average(year,month,cycle_length,num_cycles,item):
    weekly_sales = []
    start_day = find_first_monday(year,month)
    print('First Monday of the Month: ',start_day)
    _, last_day = calendar.monthrange(year, month)
    for i in range(0,num_cycles):
        week_total = 0
        for j in range(start_day,start_day + cycle_length):

            try:
                week_total = week_total + daily.loc[(month,j,item),'Qty'].values[0]

            except KeyError:
                continue



        start_day = start_day + cycle_length
        if start_day>last_day:
            month = month+1
            initial_start = start_day - cycle_length
            days_accounted = last_day - initial_start
            remaining_days = cycle_length - days_accounted -1
            for k in range(1,remaining_days+1):
                try:
                    week_total = week_total + daily.loc[(month,k,item),'Qty'].values[0]
                except KeyError:
                    continue
                    
        print(f"period: {month}/{start_day} week: {i} total_sales: {week_total}")
        weekly_sales.append(week_total)
    return weekly_sales

In [5]:
df = get_data()


##accounting only for cigarretes
filtered_df = df[(df['Department'] == 'Cigarettes') | (df['Department'] == 'MARLBORO')]
items = filtered_df['Scan Code'].unique()
daily = filtered_df.groupby(['Month','Day','Scan Code','Description','Department']).agg({'Qty':'sum'})
daily

Year(s) :  [2023]
Months(s) :  [ 9 10]
start date:  2023-09-01 07:11:20
end date:  2023-10-31 22:33:21

                                                           Qty
Month Day Scan Code    Description             Department
9     1   012300000932 CAMEL MEN KS BOX        Cigarettes    4
          012300000949 CAMEL MEN SILVER KS BOX Cigarettes    1
          012300197410 CAMEL CRUSH  BOX        Cigarettes    5
          020400000349 MISTY BLUE 120 BOX      Cigarettes    1
          026100005738 NEWPORT 100 BOX         Cigarettes   18
...                                                        ...
10    31  090500000877 KOOL BLUE 100 BOX       Cigarettes    1
          090500000907 SALEM REGULAR SHORT BOX Cigarettes    1
          090500000945 SALEM GOLD 100 BOX      Cigarettes    2
          090500010005 kool $.50 off ks box    Cigarettes    4
          090500010012 kool $.50 off 100 box   Cigarettes    2

[1806 rows x 1 columns]

In [8]:
items = filtered_df['Scan Code'].unique()
item_record = filtered_df.set_index('Scan Code')

In [14]:
records = []
for item in items:
    print(item)
    print(item_record.loc[(item,'Description')].values[0])
    weekly_sales = calculate_cycle_average(2023,9,7,4,item)
    records.append({
        item:weekly_sales
    })
    print('\n')

print(records)

090500000860
KOOL BLUE SHORT BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 15
period: 9/18 week: 1 total_sales: 11
period: 9/25 week: 2 total_sales: 5
period: 10/32 week: 3 total_sales: 2


026100005738
NEWPORT 100 BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 71
period: 9/18 week: 1 total_sales: 56
period: 9/25 week: 2 total_sales: 62
period: 10/32 week: 3 total_sales: 76


090500000730
KOOL 100 BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 26
period: 9/18 week: 1 total_sales: 29
period: 9/25 week: 2 total_sales: 34
period: 10/32 week: 3 total_sales: 20


026100005752
NEWPORT BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 59
period: 9/18 week: 1 total_sales: 57
period: 9/25 week: 2 total_sales: 57
period: 10/32 week: 3 total_sales: 66


028200005687
MARLBORO SPCL BL RED 100 BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 22
period: 9/18 week: 1 total_sales: 19
period: 9/25 week: 2 total_sales: 27
period: 10/32 week: 3 total_sales: 41


026100006568
NEWPORT NON-MENTHOL BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 9
period: 9/18 week: 1 total_sales: 5
period: 9/25 week: 2 total_sales: 3
period: 10/32 week: 3 total_sales: 8


090500000914
SALEM REG 100
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 0
period: 9/18 week: 1 total_sales: 0
period: 9/25 week: 2 total_sales: 0
period: 10/32 week: 3 total_sales: 0


028200003577
MARLBORO RED SHORT BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 37
period: 9/18 week: 1 total_sales: 43
period: 9/25 week: 2 total_sales: 53
period: 10/32 week: 3 total_sales: 39


028200003638
MARLBORO RED 100 BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 24
period: 9/18 week: 1 total_sales: 31
period: 9/25 week: 2 total_sales: 25
period: 10/32 week: 3 total_sales: 29


012300000949
CAMEL MEN SILVER KS BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 8
period: 9/18 week: 1 total_sales: 9
period: 9/25 week: 2 total_sales: 6
period: 10/32 week: 3 total_sales: 5


028200003645
MARLBORO MEN 100 BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 9
period: 9/18 week: 1 total_sales: 10
period: 9/25 week: 2 total_sales: 9
period: 10/32 week: 3 total_sales: 6


012300000932
CAMEL MEN KS BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 5
period: 9/18 week: 1 total_sales: 4
period: 9/25 week: 2 total_sales: 11
period: 10/32 week: 3 total_sales: 3


028200004239
MARLBORO SPCL BL GOLD 100 BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 11
period: 9/18 week: 1 total_sales: 15
period: 9/25 week: 2 total_sales: 13
period: 10/32 week: 3 total_sales: 15


812615006823
RACER MILD 100 BOX CT
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 1
period: 9/18 week: 1 total_sales: 2
period: 9/25 week: 2 total_sales: 1
period: 10/32 week: 3 total_sales: 2


028200310224
L&M BLUE 100 BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 0
period: 9/18 week: 1 total_sales: 2
period: 9/25 week: 2 total_sales: 0
period: 10/32 week: 3 total_sales: 1


028200004222
MARLBORO SPCL BL GOLD SHORT
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 20
period: 9/18 week: 1 total_sales: 13
period: 9/25 week: 2 total_sales: 18
period: 10/32 week: 3 total_sales: 14


028200003843
MARLBORO GOLD SHORT BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 35
period: 9/18 week: 1 total_sales: 32
period: 9/25 week: 2 total_sales: 32
period: 10/32 week: 3 total_sales: 36


090500000617
WINSTON GOLD 100 BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 2
period: 9/18 week: 1 total_sales: 1
period: 9/25 week: 2 total_sales: 0
period: 10/32 week: 3 total_sales: 0


028200317728
MARLBORO NXT BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 14
period: 9/18 week: 1 total_sales: 20
period: 9/25 week: 2 total_sales: 12
period: 10/32 week: 3 total_sales: 22


026100016222
NEWPORT PLATINUM BLUE 100'S
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 1
period: 9/18 week: 1 total_sales: 1
period: 9/25 week: 2 total_sales: 0
period: 10/32 week: 3 total_sales: 2


026100016284
newport platinum blue box
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 2
period: 9/18 week: 1 total_sales: 3
period: 9/25 week: 2 total_sales: 1
period: 10/32 week: 3 total_sales: 1


020400000349
MISTY BLUE 120 BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 10
period: 9/18 week: 1 total_sales: 0
period: 9/25 week: 2 total_sales: 8
period: 10/32 week: 3 total_sales: 10


090500000716
KOOL SHORT BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 16
period: 9/18 week: 1 total_sales: 34
period: 9/25 week: 2 total_sales: 22
period: 10/32 week: 3 total_sales: 10


028200004659
MARLBORO GOLD 100 BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 16
period: 9/18 week: 1 total_sales: 28
period: 9/25 week: 2 total_sales: 14
period: 10/32 week: 3 total_sales: 19


028200005656
MARLBORO SPCL BL RED SHORT BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 10
period: 9/18 week: 1 total_sales: 18
period: 9/25 week: 2 total_sales: 5
period: 10/32 week: 3 total_sales: 31


028200009524
MARLBORO BLACK RED SHORTS
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 3
period: 9/18 week: 1 total_sales: 4
period: 9/25 week: 2 total_sales: 2
period: 10/32 week: 3 total_sales: 7


090500010128
winston - 100 50c off red
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 1
period: 9/18 week: 1 total_sales: 0
period: 9/25 week: 2 total_sales: 0
period: 10/32 week: 3 total_sales: 0


090500000518
MAVERICK MEN 100 BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 2
period: 9/18 week: 1 total_sales: 0
period: 9/25 week: 2 total_sales: 2
period: 10/32 week: 3 total_sales: 3


012300197410
CAMEL CRUSH  BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 9
period: 9/18 week: 1 total_sales: 11
period: 9/25 week: 2 total_sales: 10
period: 10/32 week: 3 total_sales: 10


028200009531
MARLBORO BLACK RED 100
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 2
period: 9/18 week: 1 total_sales: 0
period: 9/25 week: 2 total_sales: 1
period: 10/32 week: 3 total_sales: 10


028200310026
L&M BLUE SHORT BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 0
period: 9/18 week: 1 total_sales: 1
period: 9/25 week: 2 total_sales: 0
period: 10/32 week: 3 total_sales: 1


090500010074
Winston Red Shorts $.50 off Shorts Box
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 1
period: 9/18 week: 1 total_sales: 1
period: 9/25 week: 2 total_sales: 2
period: 10/32 week: 3 total_sales: 4


028200004017
MARLBORO MEN GOLD KS BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 4
period: 9/18 week: 1 total_sales: 2
period: 9/25 week: 2 total_sales: 2
period: 10/32 week: 3 total_sales: 2


028200007230
BH MEN 100 BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 3
period: 9/18 week: 1 total_sales: 3
period: 9/25 week: 2 total_sales: 3
period: 10/32 week: 3 total_sales: 4


028200009623
MARLBORO MEN 72 BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 3
period: 9/18 week: 1 total_sales: 5
period: 9/25 week: 2 total_sales: 5
period: 10/32 week: 3 total_sales: 4


028200009357
marlb 72 black mtl
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 10
period: 9/18 week: 1 total_sales: 3
period: 9/25 week: 2 total_sales: 4
period: 10/32 week: 3 total_sales: 4


027200002177
capri ment 120 fsc indigo
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 3
period: 9/18 week: 1 total_sales: 2
period: 9/25 week: 2 total_sales: 3
period: 10/32 week: 3 total_sales: 0


028200004789
MARLBORO SILVER 100 BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 8
period: 9/18 week: 1 total_sales: 9
period: 9/25 week: 2 total_sales: 2
period: 10/32 week: 3 total_sales: 2


028200009548
MARLBORO BLK MEN SHORT BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 3
period: 9/18 week: 1 total_sales: 0
period: 9/25 week: 2 total_sales: 1
period: 10/32 week: 3 total_sales: 1


090500000723
KOOL SOFT SHORT
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 3
period: 9/18 week: 1 total_sales: 3
period: 9/25 week: 2 total_sales: 5
period: 10/32 week: 3 total_sales: 1


026100006704
NEWPORT SMOOTH SELECT SHORTS
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 0
period: 9/18 week: 1 total_sales: 3
period: 9/25 week: 2 total_sales: 2
period: 10/32 week: 3 total_sales: 3


028200309921
L&M RED 100 BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 11
period: 9/18 week: 1 total_sales: 3
period: 9/25 week: 2 total_sales: 4
period: 10/32 week: 3 total_sales: 3


028200004772
MARLBORO SILVER SHORT BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 3
period: 9/18 week: 1 total_sales: 9
period: 9/25 week: 2 total_sales: 9
period: 10/32 week: 3 total_sales: 3


047995855253
AMERICAN SPRT ORG LT
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 0
period: 9/18 week: 1 total_sales: 0
period: 9/25 week: 2 total_sales: 1
period: 10/32 week: 3 total_sales: 0


028200003232
MARLBORO SMOOTH BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 1
period: 9/18 week: 1 total_sales: 4
period: 9/25 week: 2 total_sales: 1
period: 10/32 week: 3 total_sales: 1


027200002399
CAPRI MENT 100 FSC INDIGO
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 2
period: 9/18 week: 1 total_sales: 3
period: 9/25 week: 2 total_sales: 2
period: 10/32 week: 3 total_sales: 0


028200309822
L&M RED SHORT BOX
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 1
period: 9/18 week: 1 total_sales: 0
period: 9/25 week: 2 total_sales: 1
period: 10/32 week: 3 total_sales: 1


028200331328
marlboro bold ice box
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 6
period: 9/18 week: 1 total_sales: 3
period: 9/25 week: 2 total_sales: 3
period: 10/32 week: 3 total_sales: 5


812615006809
RACER RED 100 BOX CT
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 2
period: 9/18 week: 1 total_sales: 0
period: 9/25 week: 2 total_sales: 1
period: 10/32 week: 3 total_sales: 1


026100005783
NEWPORT MENTHOL SHORTS SOFT PACK
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 1
period: 9/18 week: 1 total_sales: 0
period: 9/25 week: 2 total_sales: 1
period: 10/32 week: 3 total_sales: 0


027200002160
CAPRI MAGENTA 120
First Monday of the Month:  4
period: 9/11 week: 0 total_sales: 1
period: 9/18 week: 1 total_sales: 1
period: 9/25 week: 2 total_sales: 1
period: 10/32 week: 3 total_sales: 0


090500000594

AttributeError: 'str' object has no attribute 'values'

In [86]:
calculate_cycle_average(2023,9,7,4,'090500000730')

First Monday of the Month:  4
period: 10/11 week: 0 total_sales: 36
period: 10/18 week: 1 total_sales: 43
period: 10/25 week: 2 total_sales: 23
period: 10/32 week: 3 total_sales: 25

[36, 43, 23, 25]

In [85]:
calculate_cycle_average(2023,10,7,4,'090500000730')

First Monday of the Month:  2
period: 10/9 week: 0 total_sales: 42
period: 10/16 week: 1 total_sales: 43
period: 10/23 week: 2 total_sales: 24
period: 10/30 week: 3 total_sales: 21

[42, 43, 24, 21]

In [14]:
print(daily.loc[(9,0,'012300000932'),'Qty'].values[0])

3

In [15]:
items = df['Scan Code'].unique()

In [ ]:
start_day = 
for item in items:
    weekly_total = 0
    for i in range(0,7):
        weekly_total = weekly_total